import { Device, DeviceStatus, Credentials } from './types';

export const INITIAL_DEVICES: Device[] = [
  { id: 1, name: 'PS-1', status: DeviceStatus.Available },
  { id: 2, name: 'PS-2', status: DeviceStatus.Available },
  { id: 3, name: 'PS-3', status: DeviceStatus.Busy },
  { id: 4, name: 'PS-4', status: DeviceStatus.Maintenance },
  { id: 5, name: 'PS-5', status: DeviceStatus.Available },
];

export const INITIAL_PRICES = {
  double: 20, // per hour
  quad: 30,   // per hour
};

export const INITIAL_CREDENTIALS: Credentials = {
  loginUser: 'admin',
  loginPass: 'admin',
  adminPass: '12',
};

export const INITIAL_LABELS = {
  dashboard: "لوحة التحكم",
  reports: "التقارير",
  admin: "الإدارة",
  theme_switcher: "تغيير المظهر",
  login_page_title: "تسجيل دخول - نظام صالة الألعاب",
  username: "اسم المستخدم",
  password: "كلمة المرور",
  login: "دخول",
  device: "جهاز",
  available: "متاح",
  busy: "مشغول",
  maintenance: "تحت الصيانة",
  start_session: "بدء جلسة",
  end_session: "إنهاء الجلساة",
  session_details: "تفاصيل الجلسة",
  game_type: "نوع اللعب",
  double: "زوجي",
  quad: "رباعي",
  time_mode: "نمط التوقيت",
  open_time: "وقت مفتوح",
  timed: "محدد",
  duration_minutes: "المدة (دقائق)",
  cancel: "إلغاء",
  start: "بدء",
  time_remaining: "الوقت المتبقي",
  session_time_ended_for: "انتهى وقت الجلسة للجهاز",
  choose_action: "اختر الإجراء المناسب.",
  switch_to_open_time: "تحويل لوقت مفتوح",
  extend_time: "تمديد الوقت",
  stop_session: "إيقاف الجلسة",
  extend_session_for: "تمديد الجلسة للجهاز",
  additional_time: "الوقت الإضافي",
  confirm_extension: "تأكيد التمديد",
  total_revenue_for: "إجمالي الإيرادات ليوم",
  no_reports_for_selected_date: "لا توجد تقارير للتاريخ المحدد.",
  print_pdf: "طباعة PDF",
  print_html: "طباعة صفحة ويب",
  report_details: "تفاصيل التقرير",
  date: "التاريخ",
  device_id: "رقم الجهاز",
  start_time: "وقت البدء",
  end_time: "وقت الإنتهاء",
  duration: "المدة",
  cost: "التكلفة",
  total: "الإجمالي",
  admin_panel: "لوحة تحكم المدير",
  enter_admin_password: "الرجاء إدخال كلمة مرور المدير للوصول",
  submit: "إرسال",
  price_management: "إدارة الأسعار",
  double_price_per_hour: "سعر اللعب الزوجي (للساعة)",
  quad_price_per_hour: "سعر اللعب الرباعي (للساعة)",
  update_prices: "تحديث الأسعار",
  device_management: "إدارة الأجهزة",
  add_new_device: "إضافة جهاز جديد",
  add: "إضافة",
  reports_management: "إدارة التقارير",
  delete_all_reports: "حذف جميع التقارير",
  confirm_delete_all_reports: "هل أنت متأكد من رغبتك في حذف جميع التقارير؟ لا يمكن التراجع عن هذا الإجراء.",
  confirm_delete: "تأكيد الحذف",
  label_management: "إدارة التسميات",
  page_title: "عنوان الصفحة",
  label_text: "نص التسمية",
  save_labels: "حفظ التسميات",
  confirm_end_session: "تأكيد إنهاء الجلسة",
  confirm: "تأكيد",
  minute_short: "دقيقة",
  session_will_end_in: "سيتم إنهاء الجلسة تلقائياً خلال {0} ثواني.",
  end_session_now: "إنهاء الجلسة الآن",
  password_management: "إدارة كلمات المرور",
  login_username: "اسم مستخدم الدخول",
  login_password: "كلمة سر الدخول",
  admin_panel_password: "كلمة سر لوحة الإدارة",
  save_and_export_pdf: "حفظ وتصدير PDF",
  password_change_report: "تقرير تغيير كلمة المرور",
  changes_made_on: "التغييرات التي تمت بتاريخ",
  new_login_username: "اسم مستخدم الدخول الجديد",
  new_login_password: "كلمة سر الدخول الجديدة",
  new_admin_password: "كلمة سر الإدارة الجديدة",
  store_securely_warning: "هام: يرجى تخزين هذه المعلومات في مكان آمن. لا يمكن استعادتها.",
  player_name: "اسم اللاعب",
  passwords_updated_success: "تم تحديث كلمات المرور بنجاح!",
};